var searchData=
[
  ['unary_5fcompose_0',['unary_compose',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08462.html',1,'__gnu_cxx']]],
  ['unary_5ffunction_1',['unary_function',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5flimit_2c_20size_5ft_20_3e_2',['unary_function&lt; __gnu_cxx::throw_value_limit, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5f_5fgnu_5fcxx_3a_3athrow_5fvalue_5frandom_2c_20size_5ft_20_3e_3',['unary_function&lt; __gnu_cxx::throw_value_random, size_t &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3afirst_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e_4',['unary_function&lt; _Operation::first_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5foperation_3a_3asecond_5fargument_5ftype_2c_20_5foperation_3a_3aresult_5ftype_20_3e_5',['unary_function&lt; _Operation::second_argument_type, _Operation::result_type &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5fpredicate_3a_3aargument_5ftype_2c_20bool_20_3e_6',['unary_function&lt; _Predicate::argument_type, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_20_2a_2c_20_5fret_20_3e_7',['unary_function&lt; _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5fret_20_3e_8',['unary_function&lt; _Tp, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20_5ftp_20_3e_9',['unary_function&lt; _Tp, _Tp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20_5ftp_2c_20bool_20_3e_10',['unary_function&lt; _Tp, bool &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5ffunction_3c_20const_20_5ftp_20_2a_2c_20_5fret_20_3e_11',['unary_function&lt; const _Tp *, _Ret &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06746.html',1,'std']]],
  ['unary_5fnegate_12',['unary_negate',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a06986.html',1,'std']]],
  ['unbalanced_5ftag_13',['unbalanced_tag',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a09022.html',1,'__gnu_parallel']]],
  ['underflow_5ferror_14',['underflow_error',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02914.html',1,'std']]],
  ['underlying_5ftype_15',['underlying_type',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03678.html',1,'std']]],
  ['uniform_5fint_5fdistribution_16',['uniform_int_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07498.html',1,'std']]],
  ['uniform_5freal_5fdistribution_17',['uniform_real_distribution',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05490.html',1,'std']]],
  ['unique_5flock_18',['unique_lock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07506.html',1,'std']]],
  ['unique_5fptr_19',['unique_ptr',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20_5ftp_5b_5d_2c_20_5fdp_20_3e_20',['unique_ptr&lt; _Tp[], _Dp &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07522.html',1,'std']]],
  ['unique_5fptr_3c_20argumentexpressionlist_20_3e_21',['unique_ptr&lt; ArgumentExpressionList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20arraylength_20_3e_22',['unique_ptr&lt; ArrayLength &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20classargumentlist_20_3e_23',['unique_ptr&lt; ClassArgumentList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20classdeclstart_20_3e_24',['unique_ptr&lt; ClassDeclStart &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20classmemberdeclarationlist_20_3e_25',['unique_ptr&lt; ClassMemberDeclarationList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20codegeneratorllvmcontext_20_3e_26',['unique_ptr&lt; CodeGeneratorLLVMContext &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20enumdefinitionvaluelist_20_3e_27',['unique_ptr&lt; EnumDefinitionValueList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20expression_20_3e_28',['unique_ptr&lt; Expression &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20filestatementfunctiondeclstart_20_3e_29',['unique_ptr&lt; FileStatementFunctionDeclStart &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20globalinitializer_20_3e_30',['unique_ptr&lt; GlobalInitializer &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3acontext_3a_3aerrors_20_3e_31',['unique_ptr&lt; Gyoji::context::Errors &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3acontext_3a_3atokenstream_20_3e_32',['unique_ptr&lt; Gyoji::context::TokenStream &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3alowering_3a_3afunctionpoint_20_3e_33',['unique_ptr&lt; Gyoji::frontend::lowering::FunctionPoint &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3alowering_3a_3ascope_20_3e_34',['unique_ptr&lt; Gyoji::frontend::lowering::Scope &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3anamespaces_3a_3ans2context_20_3e_35',['unique_ptr&lt; Gyoji::frontend::namespaces::NS2Context &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3anamespaces_3a_3ans2entity_20_3e_36',['unique_ptr&lt; Gyoji::frontend::namespaces::NS2Entity &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3aaccessmodifier_20_3e_37',['unique_ptr&lt; Gyoji::frontend::tree::AccessModifier &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3aaccessqualifier_20_3e_38',['unique_ptr&lt; Gyoji::frontend::tree::AccessQualifier &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3afilestatementlist_20_3e_39',['unique_ptr&lt; Gyoji::frontend::tree::FileStatementList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3afunctiondefinitionarglist_20_3e_40',['unique_ptr&lt; Gyoji::frontend::tree::FunctionDefinitionArgList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3astatementifelse_20_3e_41',['unique_ptr&lt; Gyoji::frontend::tree::StatementIfElse &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3aterminal_20_3e_42',['unique_ptr&lt; Gyoji::frontend::tree::Terminal &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3atranslationunit_20_3e_43',['unique_ptr&lt; Gyoji::frontend::tree::TranslationUnit &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3atypename_20_3e_44',['unique_ptr&lt; Gyoji::frontend::tree::TypeName &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3atypespecifier_20_3e_45',['unique_ptr&lt; Gyoji::frontend::tree::TypeSpecifier &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3atypespecifiercallargs_20_3e_46',['unique_ptr&lt; Gyoji::frontend::tree::TypeSpecifierCallArgs &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3atypespecifierlist_20_3e_47',['unique_ptr&lt; Gyoji::frontend::tree::TypeSpecifierList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3afrontend_3a_3atree_3a_3aunsafemodifier_20_3e_48',['unique_ptr&lt; Gyoji::frontend::tree::UnsafeModifier &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20gyoji_3a_3amir_3a_3afunction_20_3e_49',['unique_ptr&lt; Gyoji::mir::Function &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20initializerexpression_20_3e_50',['unique_ptr&lt; InitializerExpression &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20llvm_3a_3airbuilder_3c_3e_20_3e_51',['unique_ptr&lt; llvm::IRBuilder&lt;&gt; &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20llvm_3a_3allvmcontext_20_3e_52',['unique_ptr&lt; llvm::LLVMContext &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20llvm_3a_3amodule_20_3e_53',['unique_ptr&lt; llvm::Module &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20namespacedeclaration_20_3e_54',['unique_ptr&lt; NamespaceDeclaration &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20scopebody_20_3e_55',['unique_ptr&lt; ScopeBody &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20statementlist_20_3e_56',['unique_ptr&lt; StatementList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20statementswitchcontent_20_3e_57',['unique_ptr&lt; StatementSwitchContent &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20structinitializerexpression_20_3e_58',['unique_ptr&lt; StructInitializerExpression &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20structinitializerfieldlist_20_3e_59',['unique_ptr&lt; StructInitializerFieldList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20structinitializerlist_20_3e_60',['unique_ptr&lt; StructInitializerList &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unique_5fptr_3c_20usingas_20_3e_61',['unique_ptr&lt; UsingAs &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07518.html',1,'std']]],
  ['unordered_5fmap_62',['unordered_map',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08398.html',1,'std::__debug::unordered_map&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07538.html',1,'std::unordered_map&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fmultimap_63',['unordered_multimap',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08402.html',1,'std::__debug::unordered_multimap&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07534.html',1,'std::unordered_multimap&lt; typename _Key, typename _Tp, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fmultiset_64',['unordered_multiset',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08418.html',1,'std::__debug::unordered_multiset&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07550.html',1,'std::unordered_multiset&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unordered_5fset_65',['unordered_set',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a08414.html',1,'std::__debug::unordered_set&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;'],['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a07554.html',1,'std::unordered_set&lt; typename _Value, typename _Hash, typename _Pred, typename _Alloc &gt;']]],
  ['unsafemodifier_66',['UnsafeModifier',['../classGyoji_1_1frontend_1_1tree_1_1UnsafeModifier.html',1,'Gyoji::frontend::tree']]],
  ['unsynchronized_5fpool_5fresource_67',['unsynchronized_pool_resource',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02798.html',1,'std::pmr']]],
  ['uses_5fallocator_68',['uses_allocator',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a05150.html',1,'std']]],
  ['uses_5fallocator_3c_20tuple_3c_20_5ftypes_2e_2e_2e_20_3e_2c_20_5falloc_20_3e_69',['uses_allocator&lt; tuple&lt; _Types... &gt;, _Alloc &gt;',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a03058.html',1,'std']]],
  ['utc_5fclock_70',['utc_clock',['http://gcc.gnu.org/onlinedocs/libstdc++/latest-doxygen/a02086.html',1,'std::chrono']]]
];
